//By:Ali Rajabpour-Sanati | ali.poursanati@gmail.com
//@version=4
study(title="ARPS Ultimate Signal Framework (USF)", shorttitle="ARPS USF")

osc_counter = 0.0
// ***********************************************************************************
//------------------------- Adaptive ATR-ADX Trend -----------------------------//

CalcATR_ADX = input(true, title="Calculate Adaptive 4H ATR-ADX Trend")

//Mode
atrLen = 14  //"ATR", minval = 1, maxval = 100
m1 = 3.5  //"ATR Multiplier - ADX Rising", minval = 1, step = 0.1, maxval = 100
m2 = 1.75  //"ATR Multiplier - ADX Falling", minval = 1, step = 0.1, maxval = 100
dintval = "240"  //"Inverval (i.e. 15, 60, 240, D, W)
useIntval = false  //"Use Chart Interval"

bandHalfWidth = 1  //1, "Band Pip/Tick Size Around Stop", minval = 0
showBand = false  //"Use Band Around Stop?"

adxLen = 14  //"ADX", defval = 14, minval = 1, maxval = 100
adxThresh = 25  //"ADX Threshold", defval = 25, minval = 1
aboveThresh = true  //"ADX Above Threshold uses ATR Falling Multiplier Even if Rising?"
useHeikin = true  //"Use Heikin-Ashi Bars (Source will be ohlc4)"

src = ohlc4

tk = syminfo.mintick
blockMult = tk < 0.1 and 
   (tk != 0.01 or syminfo.pointvalue < 10 or syminfo.pointvalue * tk <= 1) and 
   (tk != 0.001 or syminfo.pointvalue <= 1) and tk != 0.005 and tk != 0.0001 and 
   tk != 0.0005 and tk != 0.03125 and tk != 0.015625 ? 
   tk == 0.00005 or tk * 100 == 0.00005 ? 2 : 10 : 1
block = tk * blockMult

atrCalc() =>
    // DI-Pos, DI-Neg, ADX

    hR = change(high)
    lR = -change(low)

    dmPos = hR > lR ? max(hR, 0) : 0
    dmNeg = lR > hR ? max(lR, 0) : 0

    sTR = tr
    sTR := nz(sTR[1]) - nz(sTR[1]) / adxLen + tr
    sDMPos = tr
    sDMPos := nz(sDMPos[1]) - nz(sDMPos[1]) / adxLen + dmPos
    sDMNeg = tr
    sDMNeg := nz(sDMNeg[1]) - nz(sDMNeg[1]) / adxLen + dmNeg

    DIP = sDMPos / sTR * 100
    DIN = sDMNeg / sTR * 100
    DX = abs(DIP - DIN) / (DIP + DIN) * 100
    adx = sma(DX, adxLen)

    // Heikin-Ashi

    xClose = ohlc4
    xOpen = open
    xOpen := (nz(xOpen[1]) + nz(xClose[1])) / 2
    xHigh = max(high, max(xOpen, xClose))
    xLow = min(low, min(xOpen, xClose))

    // Trailing ATR

    v1 = abs(xHigh - xClose[1])
    v2 = abs(xLow - xClose[1])
    v3 = xHigh - xLow

    trueRange = max(v1, max(v2, v3))
    rma_1 = rma(trueRange, atrLen)
    atr_1 = atr(atrLen)
    atr = useHeikin ? rma_1 : atr_1

    m = m1
    falling_1 = falling(adx, 1)
    m := rising(adx, 1) and (adx < adxThresh or not aboveThresh) ? m1 : 
       falling_1 or adx > adxThresh and aboveThresh ? m2 : nz(m[1])
    mUp = DIP >= DIN ? m : m2
    mDn = DIN >= DIP ? m : m2

    src_ = useHeikin ? (xOpen + xHigh + xLow + xClose) / 4 : src
    c = useHeikin ? xClose : close
    t = useHeikin ? (xHigh + xLow) / 2 : hl2

    up = t - mUp * atr
    dn = t + mDn * atr

    TUp = close
    TUp := max(src_[1], max(c[1], close[1])) > TUp[1] ? max(up, TUp[1]) : up
    TDown = close
    TDown := min(src_[1], min(c[1], close[1])) < TDown[1] ? min(dn, TDown[1]) : dn

    trend = 1
    trend := min(src_, min(c, close)) > TDown[1] ? 1 : 
       max(src_, max(c, close)) < TUp[1] ? -1 : nz(trend[1], 1)

    // ceil positive trend to nearest pip/tick, floor negative trend to nearest pip/tick
    stop = trend == 1 ? ceil(TUp / block) * block : floor(TDown / block) * block
    trendChange = change(trend)

    [adx, trend, stop, trendChange]

[adx, _trend, _stop, _trendChange] = atrCalc()

start = security(syminfo.tickerid, dintval, time, lookahead=true)
newSession = iff(change(start), 1, 0)
sinceNew = barssince(newSession)

// Fixes intervals that are uneven, i.e. 120 on normal 6.5 hour NYSE day
// This will happen if a 2H interval closes at 4:00 EST but opened at 3:30
// EST. This is a new session candle. The 9:30 open the next day will also
// be a new session candle, which shouldn't happen. There should never be
// 2 consecutive candles that are new session candles, unless the indicator
// interval is less than or equal to the chart interval. If there are 3
// consecutive candles where each candle is a new session, then the chart
// interval is <= the declared indicator interval.
isChartIntval = sinceNew == 0 and sinceNew[1] == 0 and sinceNew[2] == 0

security_1 = security(syminfo.tickerid, dintval, _trend[1], lookahead=true)
trend = useIntval or isChartIntval ? _trend : security_1
security_2 = security(syminfo.tickerid, dintval, _stop[1], lookahead=true)
stop = useIntval or isChartIntval ? _stop : security_2
security_3 = security(syminfo.tickerid, dintval, _trendChange[1], lookahead=true)
trendChange = useIntval or isChartIntval ? _trendChange : security_3

// Plot

upC = #00FF00DD
dnC = #FF0000DD
upC2 = #00FF0037
dnC2 = #FF000037
trans = #00000000

lineColor = not trendChange or trendChange[1] ? trend > 0 ? upC : dnC : trans
fillColor = not trendChange or trendChange[1] ? trend > 0 ? upC2 : dnC2 : trans

// Can't figure out any other way to solve this issue for fixing a problem where
// the indicator interval is greater than the chart interval, and the indicator is
// not divisible by the chart interval without a remainder.
oddIntervalTest = lineColor[1] == upC and lineColor[0] == dnC or 
   lineColor[1] == dnC and lineColor[0] == upC
stopColor = oddIntervalTest ? trans : lineColor
trendChangeReal = stopColor == trans
shapeColor = trendChangeReal ? trend > 0 ? #00FF00F8 : #FF0000F8 : trans

upperBand = stop + bandHalfWidth * block
lowerBand = stop - bandHalfWidth * block


if CalcATR_ADX and (not trendChange or trendChange[1])
	if trend > 0
		osc_counter := osc_counter + 1
	else
		osc_counter := osc_counter - 1
else
	osc_counter := osc_counter

// ***********************************************************************************
//------------------------- 200|50 EMAs Crosses -----------------------------//

CalcEMA_30_Crosses = input(true, title="Calculate 30m ZEMAs Crosses")
CalcEMA_4_Crosses = input(true, title="Calculate 4h ZEMAs Crosses")
CalcEMA_d_Crosses = input(true, title="Calculate D ZEMAs Crosses")

//ZEMA-50 in 30 minutes timeframe 
temp_EMA_50_30_1 = security(syminfo.tickerid,"30",ema(close, 50))
temp_EMA_50_30_2 = ema(temp_EMA_50_30_1, 50)
Difference_50_30 = temp_EMA_50_30_1 - temp_EMA_50_30_2
ZEMA_50_30 = temp_EMA_50_30_1 + Difference_50_30

//ZEMA-200 in 30 minutes timeframe 
temp_EMA_200_30_1 = security(syminfo.tickerid,"30",ema(close, 200))
temp_EMA_200_30_2 = ema(temp_EMA_200_30_1, 200)
Difference_200_30 = temp_EMA_200_30_1 - temp_EMA_200_30_2
ZEMA_200_30 = temp_EMA_200_30_1 + Difference_200_30

//ZEMA-50 in 4 hours timeframe 
temp_EMA_50_4_1 = security(syminfo.tickerid,"240",ema(close, 50))
temp_EMA_50_4_2 = ema(temp_EMA_50_4_1, 50)
Difference_50_4 = temp_EMA_50_4_1 - temp_EMA_50_4_2
ZEMA_50_4 = temp_EMA_50_4_1 + Difference_50_4

//ZEMA-200 in 4 hours timeframe 
temp_EMA_200_4_1 = security(syminfo.tickerid,"240",ema(close, 200))
temp_EMA_200_4_2 = ema(temp_EMA_200_4_1, 200)
Difference_200_4 = temp_EMA_200_4_1 - temp_EMA_200_4_2
ZEMA_200_4 = temp_EMA_200_4_1 + Difference_200_4

//ZEMA-50 in daily timeframe 
temp_EMA_50_d_1 = security(syminfo.tickerid,"D",ema(close, 50))
temp_EMA_50_d_2 = ema(temp_EMA_50_d_1, 50)
Difference_50_d = temp_EMA_50_d_1 - temp_EMA_50_d_2
ZEMA_50_d = temp_EMA_50_d_1 + Difference_50_d

//ZEMA-200 in daily timeframe 
temp_EMA_200_d_1 = security(syminfo.tickerid,"D",ema(close, 200))
temp_EMA_200_d_2 = ema(temp_EMA_200_d_1, 200)
Difference_200_d = temp_EMA_200_d_1 - temp_EMA_200_d_2
ZEMA_200_d = temp_EMA_200_d_1 + Difference_200_d

if (CalcEMA_30_Crosses and crossover(ZEMA_50_30, ZEMA_200_30))
	osc_counter := osc_counter + 1
if (CalcEMA_30_Crosses and crossover(ZEMA_200_30, ZEMA_50_30))
	osc_counter := osc_counter - 1
	
if (CalcEMA_4_Crosses and crossover(ZEMA_50_4, ZEMA_200_4))
	osc_counter := osc_counter + 2
if (CalcEMA_4_Crosses and crossover(ZEMA_200_4, ZEMA_50_4))
	osc_counter := osc_counter - 2
	
if (CalcEMA_d_Crosses and crossover(ZEMA_50_d, ZEMA_200_d))
	osc_counter := osc_counter + 3
if (CalcEMA_d_Crosses and crossover(ZEMA_200_d, ZEMA_50_d))
	osc_counter := osc_counter - 3

// ***********************************************************************************
//------------------------- Linear Regression -----------------------------//

LinRegSource = close
length = 100
offset = 0
LinRegDev   = 2.0		//Deviation
smoothing   = 1
mtf_val     = ""		//Resolution
line_thick  = 4			//S&R Thickness
signals     = "All"		//"Signals Display", options=["Recent", "All"]
goto        = 0			//"End At Bar Index"

data(x) => sma(security(syminfo.tickerid, mtf_val!="" ? mtf_val : timeframe.period, x), smoothing)

linreg = data(linreg(LinRegSource, length, offset))
linreg_p = data(linreg(LinRegSource, length, offset+1))
//plot(linreg, "Regression Line", linreg>linreg[1]?color.green:color.red, editable=false)

x = bar_index
slope = linreg - linreg_p
intercept = linreg - x*slope
deviationSum = 0.0
for i=0 to length-1
    deviationSum:= deviationSum + pow(LinRegSource[i]-(slope*(x-i)+intercept), 2)  
deviation = sqrt(deviationSum/(length))
x1 = x-length
x2 = x
y1 = slope*(x-length)+intercept
y2 = linreg

updating = goto <= 0 or x < goto


dm_current = -deviation*LinRegDev + y2
dp_current = deviation*LinRegDev + y2
buy = crossunder(close, dm_current)
sell = crossover(close, dp_current)
    
if buy
	osc_counter := osc_counter + 1
if sell
	osc_counter := osc_counter - 1

// ***********************************************************************************
//------------------------- Ichimoku -----------------------------//
CalcIchiKumo = input(true, title="Calculate Kumo Cloud & Chikou Span")
CalcTenkanKijun = input(true, title="Calculate Tenkan Sen & Kijun Sen")

middleDonchian(Length) =>
    lower = lowest(Length)
    upper = highest(Length)
    avg(upper, lower)

conversionPeriods = 9
basePeriods = 26
laggingSpan2Periods = 52
displacement = 26
Tenkan = middleDonchian(conversionPeriods)
Kijun = middleDonchian(basePeriods)
xChikou = close
SenkouA = middleDonchian(laggingSpan2Periods)
SenkouB = (Tenkan[basePeriods] + Kijun[basePeriods]) / 2
KumoCloudColor = SenkouA[displacement] > SenkouB ? color.green : color.red
KumoCloudFill = CalcIchiKumo ? 90 : 0
//fill(A, B, KumoCloudColor, transp=KumoCloudFill, editable=false)

if CalcTenkanKijun and crossover(Tenkan, Kijun)
	osc_counter := osc_counter + 1
if CalcTenkanKijun and crossover(Kijun, Tenkan)
	osc_counter := osc_counter - 1
	
if CalcIchiKumo and crossover(SenkouA[displacement], SenkouB)
	osc_counter := osc_counter + 1
if CalcIchiKumo and crossover(SenkouB, SenkouA[displacement])
	osc_counter := osc_counter - 1

// ***********************************************************************************
//------------------------- 200-EMA -----------------------------//
Show200EMAs = input(true, title="Show Price Position to 200-EMAs")

EMA1= security(syminfo.tickerid,"30",ema(close, 200))
EMA2= security(syminfo.tickerid,"240",ema(close, 200))
EMA3= security(syminfo.tickerid,"D",ema(close, 200))

// ***********************************************************************************
//------------------------- Stochastic RSI -----------------------------//
ShowStochRSI = input(true, title="Show Stochastic RSI")

StochRSIsmoothK = 1
StochRSIsmoothD = 1
StochRSIlengthRSI = 100
StochRSIlengthStoch = 100
StochRSIsrc = close

StochRSIrsi1 = rsi(StochRSIsrc, StochRSIlengthRSI)
StochRSIk = sma(stoch(StochRSIrsi1, StochRSIrsi1, StochRSIrsi1, StochRSIlengthStoch), StochRSIsmoothK)
StochRSId = sma(StochRSIk, StochRSIsmoothD)

// ***********************************************************************************
//------------------------- Money Flow Index -----------------------------//
Calc_MFI = input(true, title="Calculate Money Flow Index")

//Inputs
MFIlength = 15
os = 20
ob = 80
//CurrentRes = true
//CustomRes = input("240", title="Custom Timeframe? Uncheck Box Above (E.g. 1M, 5D, 240 = 4Hours)")

//MFI Calc
//res = CurrentRes ? timeframe.period : CustomRes
rawMoneyFlow = hlc3 * volume

positiveMoneyFlow() =>
    a = 0.0
    a := hlc3 > hlc3[1] ? a + rawMoneyFlow : a
    a
negativeMoneyFlow() =>
    b = 0.0
    b := hlc3 < hlc3[1] ? b + rawMoneyFlow : b
    b

moneyFlowRatio = sma(positiveMoneyFlow(), MFIlength) / sma(negativeMoneyFlow(), MFIlength)

moneyFlowIndex = security(syminfo.tickerid, timeframe.period, 100 - 100 / (1 + moneyFlowRatio))

//OB/OS Identification
MFIoversold = Calc_MFI and (moneyFlowIndex[1] > os[1] and moneyFlowIndex < os)
MFIoverbought = Calc_MFI and (moneyFlowIndex[1] < ob[1] and moneyFlowIndex > ob)

if Calc_MFI and MFIoversold
	osc_counter := osc_counter + 1
if Calc_MFI and MFIoverbought
	osc_counter := osc_counter - 1

// ***********************************************************************************
//------------------------- Squeeze Momentum Indicator -----------------------------//

Calc_SQZMOM = input(true, title="Calculate Squeeze Momentum")

SQZMOMlength = 20		//BB Length
mult = 2.0		//BB MultFactor
lengthKC= 20		//KC Length
multKC = 1.5		//KC MultFactor
useTrueRange =  true		//Use TrueRange (KC)

// Calculate BB
source = close
basis = sma(source, SQZMOMlength)
dev = multKC * stdev(source, SQZMOMlength)
upperBB = basis + dev
lowerBB = basis - dev

// Calculate KC
ma = sma(source, lengthKC)
range = useTrueRange ? tr : (high - low)
rangema = sma(range, lengthKC)
upperKC = ma + rangema * multKC
lowerKC = ma - rangema * multKC

sqzOn  = (lowerBB > lowerKC) and (upperBB < upperKC)
sqzOff = (lowerBB < lowerKC) and (upperBB > upperKC)
noSqz  = (sqzOn == false) and (sqzOff == false)

val = linreg(source  -  avg(avg(highest(high, lengthKC), lowest(low, lengthKC)),sma(close,lengthKC)), lengthKC,0)

// 10 = maroon/Go Long  |  12 = Green/Go Short  |  22 = red/ExitShort  |  11 = lime/Exit Long
sqz_position = iff( val > 0, iff( val > nz(val[1]), 11, 12), iff( val < nz(val[1]), 22, 10))

sqzGoLong = sqzOff and (sqz_position == 10)
sqzGoShort = sqzOff and (sqz_position == 12)
sqzExitLong = sqzOff and (sqz_position == 11)
sqzExitShort = sqzOff and (sqz_position == 22)

if Calc_SQZMOM and sqzGoLong
	osc_counter := osc_counter + 1
if Calc_SQZMOM and sqzGoShort
	osc_counter := osc_counter - 1

// ***********************************************************************************
//------------------------------------ Wave trend ----------------------------------//

//Overbought level = 64 | Oversold Level = -64

Wave_Signals = input(true, title="Calculate WaveTrend Signals")
ap = hlc3 
esa = ema(ap, 10)
d = ema(abs(ap - esa), 10)
ci = (ap - esa) / (0.015 * d)
wt1 = ema(ci, 21)
wt2 = sma(wt1,4)

if Wave_Signals and ((wt2 < -55) and (change(wt2, 3) > 0))
	osc_counter := osc_counter + 1
if Wave_Signals and ((wt2 > 55) and (change(wt2, 3) < 0))
	osc_counter := osc_counter - 1
	
//WaveTrend Oversize	
if Wave_Signals and (wt2 < -50)
	osc_counter := osc_counter + 0.5
if Wave_Signals and (wt2 > 50)
	osc_counter := osc_counter - 0.5

// ***********************************************************************************
//-----------------------------  Parabolic SAR -------------------------------------//

Parabolic_Sar = input(true, title="Calculate Parabolic SAR")

SARout = sar(0.02, 0.02, 0.07)

if Parabolic_Sar and SARout < open
	osc_counter := osc_counter + 0.5
if Parabolic_Sar and SARout > open
	osc_counter := osc_counter - 0.5
// ***********************************************************************************
//-------------------------------  Candle Patterns----------------------------------//

Candle_patterns	= input(true, title="Calculate Candle Patterns")

//Bearish Evening Star
estar=(close[2] > open[2] and close < open and abs(close[2] - open[2]) > 4*abs(close[1] - open[1]) and abs(open - close) > 4*abs(close[1] - open[1]))

//Bullish Morning Star
mstar=(close[2] < open[2] and close > open and abs(close[2] - open[2]) > 4*abs(close[1] - open[1]) and abs(open - close) > 4*abs(close[1] - open[1]))

//Bullish Shooting Star
sstar=(high - max(open, close) >= abs(open - close) * 3 and min(close, open) - low <= abs(open - close)*0.5)

//Bearish Hammer
hammer=(abs(low - min(open, close)) >= abs(open - close) * 3 and high - max(close, open) <= abs(open - close)*0.5)

//Bearish Harami
bearH=(close[2] > open[2] and open < close[2] and open > open[2] and close < close[2] and close > open[2] and high < close[2] )

//Bullish Harami
bullH=(close[2] < open[2] and open < open[2] and open > close[2] and close < open[2] and close > close[2] and low > close[2] )

//Bearish Engulfing
bearE=(close[2] > open[2] and close < open and close[2] > close and close[2] < open and open[2] > close and open[2] < open and high[2] < open )

//Bullish Engulfing
bullE=(close[2] < open[2] and close > open and close[2] < close and close[2] > open and open[2] < close and open[2] > open and low[2] > open )

//Bearish Dark Cloud Cover
dcc=((close[2]>open[2])and(((close[2]+open[2])/2)>close)and(open>close)and(open>close[2])and(close>open[2])and((open-close)/(.001+(high-low))>0.6))


if Candle_patterns and (mstar or sstar or bullH or bullE)
	osc_counter := osc_counter + 0.25
if Candle_patterns and (estar or hammer or bearH or bearE or dcc)
	osc_counter := osc_counter - 0.25
	
// ***********************************************************************************
//-------------------------------  Hull MA -----------------------------------------//

Hullength = 50
HullSrc = close
Calc_Hull = input(true, title="Calculate Hull-T3 crossovers")
hullma = wma(2*wma(HullSrc, Hullength/2)-wma(HullSrc, Hullength), round(sqrt(Hullength)))

// ***********************************************************************************
//-------------------------------  Tillson MA --------------------------------------//

length1 = 20
a1 = 0.7

e1 = ema((high + low + 2 * close) / 4, length1)
e2 = ema(e1, length1)
e3 = ema(e2, length1)
e4 = ema(e3, length1)
e5 = ema(e4, length1)
e6 = ema(e5, length1)
c1 = -a1 * a1 * a1
c2 = 3 * a1 * a1 + 3 * a1 * a1 * a1
c3 = -6 * a1 * a1 - 3 * a1 - 3 * a1 * a1 * a1
c4 = 1 + 3 * a1 + a1 * a1 * a1 + 3 * a1 * a1
T3 = c1 * e6 + c2 * e5 + c3 * e4 + c4 * e3

col1 = T3 > T3[1]
col3 = T3 < T3[1]

if Calc_Hull and (crossover(hullma, T3) and (wt2 < 25))
	osc_counter := osc_counter + 1
if Calc_Hull and (crossover(T3, hullma) and (wt2 > -25))
	osc_counter := osc_counter - 1

// ***********************************************************************************
//------------------------------------ Labels and Arrows --------------------------------------//

//200 EMAs
//30m	
if Show200EMAs and barstate.islast and (close > EMA1)
	PriceEmaPos2 = label.new(x=time, y=open + (open * 0.0087), xloc=xloc.bar_time, text="200EMA\n(30m)", style=label.style_arrowup, color=color.green)
	label.set_x(id=PriceEmaPos2, x=label.get_x(id=PriceEmaPos2) + 18000000)
	label.set_size(PriceEmaPos2, size.normal)
	label.delete(id=PriceEmaPos2[1])
if Show200EMAs and barstate.islast and (close < EMA1)
	PriceEmaPos2 = label.new(x=time, y=open + (open * 0.0087), xloc=xloc.bar_time, text="200EMA\n(30m)", style=label.style_arrowdown, color=color.red)
	label.set_x(id=PriceEmaPos2, x=label.get_x(id=PriceEmaPos2) + 18000000)
	label.set_size(PriceEmaPos2, size.normal)
	label.delete(id=PriceEmaPos2[1])
	
//4H
if Show200EMAs and barstate.islast and (close > EMA2)
	PriceEmaPos1 = label.new(x=time, y=open + (open * 0.0087), xloc=xloc.bar_time, text="200EMA\n(4H)", style=label.style_arrowup, color=color.green)
	label.set_x(id=PriceEmaPos1, x=label.get_x(id=PriceEmaPos1) + 21600000)
	label.set_size(PriceEmaPos1, size.normal)
	label.delete(id=PriceEmaPos1[1])
if Show200EMAs and barstate.islast and (close < EMA2)
	PriceEmaPos1 = label.new(x=time, y=open + (open * 0.0087), xloc=xloc.bar_time, text="200EMA\n(4H)", style=label.style_arrowdown, color=color.red)
	label.set_x(id=PriceEmaPos1, x=label.get_x(id=PriceEmaPos1) + 21600000)
	label.set_size(PriceEmaPos1, size.normal)
	label.delete(id=PriceEmaPos1[1])
	
//D	
if Show200EMAs and barstate.islast and (close > EMA3)
	PriceEmaPos2 = label.new(x=time, y=open + (open * 0.0087), xloc=xloc.bar_time, text="200EMA\n(D)", style=label.style_arrowup, color=color.green)
	label.set_x(id=PriceEmaPos2, x=label.get_x(id=PriceEmaPos2) + 25200000)
	label.set_size(PriceEmaPos2, size.normal)
	label.delete(id=PriceEmaPos2[1])
if Show200EMAs and barstate.islast and (close < EMA3)
	PriceEmaPos2 = label.new(x=time, y=open + (open * 0.0087), xloc=xloc.bar_time, text="200EMA|\n(D)", style=label.style_arrowdown, color=color.red)
	label.set_x(id=PriceEmaPos2, x=label.get_x(id=PriceEmaPos2) + 25200000)
	label.set_size(PriceEmaPos2, size.normal)
	label.delete(id=PriceEmaPos2[1])

//StochRSI
if ShowStochRSI and barstate.islast and StochRSId > 50
	StochRSI_Position = label.new(x=time, y=open, xloc=xloc.bar_time, text="StochRSI", style=label.style_arrowup, color=color.green)
	label.set_x(id=StochRSI_Position, x=label.get_x(id=StochRSI_Position) + 27000000)
	label.set_size(StochRSI_Position, size.normal)
	label.delete(id=StochRSI_Position[1])
	
if ShowStochRSI and barstate.islast and StochRSId < 50
	StochRSI_Position = label.new(x=time, y=open, xloc=xloc.bar_time, text="StochRSI", style=label.style_arrowdown, color=color.red)
	label.set_x(id=StochRSI_Position, x=label.get_x(id=StochRSI_Position) + 27000000)
	label.set_size(StochRSI_Position, size.normal)
	label.delete(id=StochRSI_Position[1])

	
	
//Copyright
if barstate.islast
	LegendBox = label.new(x=time, y=open + (0.004 * open), xloc=xloc.bar_time, text="By:Ali Rajabpour-Sanati\nali.poursanati@gmail.com" , textalign=text.align_left, style=label.style_none, color=#f0f3fa)
	label.set_x(id=LegendBox, x=label.get_x(id=LegendBox) + 36000000)
	label.set_size(LegendBox, size.normal)
	label.delete(id=LegendBox[1])

// ***********************************************************************************
//------------------------------------ Angle of HMA --------------------------------//

Calc_AngHMA = input(true, title="Calculate Angle of HMA")

HMA_for_angle = wma(2 * wma(close, 42 / 2) - wma(close, 42), round(sqrt(42)))
rad2degree = 180 / 3.141592653589793238462643  //pi 
ang = rad2degree * atan((HMA_for_angle[0] - HMA_for_angle[2]) / atr(10)/2)

upward = ang > ang[1] and (ang > 6 or ang < -6)
downward = ang < ang[1] and (ang > 6 or ang < -6)

//color_ang = upward ? color.lime : downward ? color.red : na
exit_position = ((hullma > T3) and downward) or ((hullma < T3) and upward)
color_ang = exit_position ? color.red : na

//long_stop = ((downward and upward[1])) ? true : false
//short_stop = ((upward and downward[1])) ? true : false
//plotshape(long_stop, title = "Exit Long", text = 'Exit Long')
//plotshape(short_stop, title = "Exit Short", text = 'Exit Short')

if Calc_AngHMA and (hullma > T3) and downward
	osc_counter := osc_counter - 0.5
if Calc_AngHMA and (hullma < T3) and upward
	osc_counter := osc_counter + 0.5
	
plot(osc_counter)
// ***********************************************************************************
//------------------------------------ Alerts --------------------------------------//
